name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test

  Styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run check-format
      - run: npm run lint

  Deployment:
    needs: [Test, Styling]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/actions-hero:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker, build and push
        run: |
          echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
          docker build --target production -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: SSH EC2, Docker pull and run
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_LIVE }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo yum update -y
            sudo yum install docker -y
            sudo service docker start
            sudo docker stop app-live || true
            sudo docker rm app-live || true
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/actions-hero:${{github.sha}}
            sudo docker run -d -p 3000:3000 --name app-live ${{secrets.DOCKERHUB_USERNAME}}/actions-hero:${{github.sha}}
