name: CI

on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test

  Styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run check-format
      - run: npm run lint

  Deployment:
    needs: [Test, Styling]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Build app
        run: npm run build || echo "no build needed"

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST_LIVE }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: './src/index.js,package.json,package-lock.json'
          target: '~/app'

      - name: Install Node and PM2, Install Deps, and Restart App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_LIVE }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2
            cd ~/app
            npm ci
            pm2 restart app || pm2 start src/index.js --name app
