name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test

  Styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run check-format
      - run: npm run lint

  Preview:
    needs: [Test, Styling]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/actions-hero:${{ github.sha }}
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Log into docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --target production -t $IMAGE_NAME .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      - name: Pull and Run Docker Image on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/actions-hero:${{ github.sha }}
            sudo docker run -d --name app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/actions-hero:${{ github.sha }}

      - name: Create PR Deployment Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          message: |
            🚀 Preview available at: http://${{ secrets.EC2_HOST }}:3000
