name: Example Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 checkput repo
        uses: actions/checkout@v4
      - name: step 2 print message
        run: echo '${{toJSON(github.event)}}' | jq
        shell: bash

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1 print message
        run: echo "hello world from job 2 and step 2 [2,2]"
        shell: bash
